### PR TITLE
Example that shows how to post process avg_all files

### PR DESCRIPTION
**Pull request by kmittal2**
This simple example demonstrates how to post process files generated by avg_all. Two cases have been used:
1. pipe.usr - has inflow-outflow bcs with recirculation boundary condition and calls avg_all. It runs for 5 steps and outputs avgpipe0.f0* etc... files

2. prms.usr - this case post loads up the files output from pipe and calculates the actual rms values and TKE. Since recirculation boundary conditions were used in the first case, a mask is used in the averaging routines which ignores the contributions of GLL points in the recirculation zone.

A script genlist has been included which creates the file "avg.list" and "rms.list" with names of the files needed for prms.

This example can be modified in future to calculate more turbulence statistics from the avg*, rms* and rm2* files output by avg_all.

### CODE REVIEW

**Comment by stgeke** [comment]
Do we really need a new example to demonstrate this. I would rather prefer to add this to an existing example.

**Comment by kmittal2** [comment]
I guess it depends on wether we want to have fewer examples with each showing multiple features, or more examples with each emphasizing fewer features. Nonetheless, we should have an example which shows how to calculate different turbulence statistics etc... using avg_all files. Let me know where you think this will be a good fit.

**Comment by stgeke** [comment]
I prefer to control the number of examples. It’s easier to maintain and users have a better overview.

In this case I don’t see a good reason why we should add a new one. How about adding it to turbChannel?

On 8 Dec 2017, at 18:36, k10 <notifications@github.com <mailto:notifications@github.com> > wrote:

I guess it depends on wether we want to have fewer examples with each showing multiple features, or more examples with each emphasizing fewer features. Nonetheless, we should have an example which shows how to calculate different turbulence statistics etc... using avg_all files. Let me know where you think this will be a good fit.

**Comment by kmittal2** [comment]
sounds good.

**Comment by fischer1** [comment]
Hmmm.  I'm not against more examples.

I tend to like it when I find software where exactly the case I want to solve is already an example;
no thinking required.

I think if one example is overloaded then it's a lot to ingest for a new user.

**Comment by stgeke** [comment]
I am also not against more example if there is a good reason to add another one. I also agree that we should not overload an example with tons of features. However in this particular case I an extension of an existing example makes sense. 

On 8 Dec 2017, at 19:55, fischer1 <notifications@github.com <mailto:notifications@github.com> > wrote:

Hmmm. I'm not against more examples.

I tend to like it when I find software where exactly the case I want to solve is already an example;
no thinking required.

I think if one example is overloaded then it's a lot to ingest for a new user.

**Comment by adampep** [comment]
I'm merging this example with turbInflow

**Comment by adampep** [comment]
included in turbInflow in  b1d2e8d

**Comment by kmittal2** [comment]
Thanks @adampep

**Pull request closed without merging**
