### PR TITLE
Routines intpts and intpts_setup added to hemi.usr

### PR DESCRIPTION
**Pull request by adampep**
As these two routiens were removed from Nek5000 core I add them here

### CODE REVIEW

**Comment by stgeke** [comment]
There is wrapper defined in intp.f in the source (not compiled by default) which can be used in the .usr file.

**Comment by adampep** [comment]
OK. I will look at it.

**Comment by stgeke** [comment]
Let's deactivate the interpolation for now.
This is yet another example of an optional plug-in/add-on. Something we have discusses but not resolved yet.

**Comment by adampep** [comment]
so should we skip this test for a while?

**Comment by stgeke** [comment]
We can run the test but commenting the interpolation stuff in the example.

**Comment by adampep** [comment]
This example is about interpolation as it illustrates particle tracking, 
but I can comment it.

**Comment by adampep** [comment]
removed until interpolation interface will be defined

**Pull request closed without merging**
