### PR TITLE
updated smoother to work with any lx1

### PR DESCRIPTION
**Pull request by kmittal2**
I have updated the smoother to work with any lx1. All the required routines are in smoothlx.f which is included in the usr file.

### CODE REVIEW

**Comment by stgeke** [comment]
The smoother is quite verbose. Is all this really important or is it just for debugging?
Please try to reduce the information printed to stdout. Make use of the `loglevel` variable:

`if(loglevel.gt.2) write(6,*) ...`

Loglevel goes from 2 (standard) - 5 (fully detailed).

Can you please the README.pdf by a simple text based README. I think we should avoid PDFs if we can because Git cannot do an efficient job with this kind of files.

**Comment by fischer1** [comment]
I agree that a text-based README is good.

I'd also like to be able to include more detail in .pdfs.  Can we also supplement the
example with a pdf ?

**Comment by stgeke** [comment]
I think there are two options:

- ship the .pdf (and source?) with the example
- explain the examples more in detail e.g. in the User Guide

-----Original message-----

**Comment by kmittal2** [comment]
I agree that the details in the pdf (all of which cannot be included in the txt based README) are useful for the user. If you do not want to include the pdf in the source, we could make a pdf available on the users list or Nek5000 page and give the link to it in the README.

**Comment by stgeke** [comment]
A short text-based README about the example is usually enough. However the theory/method or a detailed how-to should go into our user guide instead.

Anyway that's something we need discuss. For now lets keep the PDF.

**Comment by stgeke** [comment]
@adampep As far as I am concerned we can merge this pr.

**Pull request merged**
