### PR TITLE
2D channel ALE

### PR DESCRIPTION
**Pull request by spatel7286**
This case demonstrates the Nek5000 ALE formulation for flow in a 2D channel with a moving indentation.  

This example contains :

1) SIZE file
2) .rea
3) .usr
4) .map
5) README - Problem description.

### CODE REVIEW

**Comment by adampep** [comment]
Sorry for the slow work on it. Could you provide .par instead of .rea. We would like to improve functionality of .par. If there is any runtime parameter missing please report it in Nek5000 issues

**Comment by stgeke** [comment]
I guess we want to add this case to short_tests as well to test:
* Moving mesh with OIFS
* ALE solver
* Moving mesh with residual projection

**Comment by fischer1** [comment]
I'm working on exactly these cases... based on the moving eddy problem from our
paper of last year.   Example is almost ready.

Paul

________________________________

**Comment by adampep** [comment]
This test case has ifheat set to true, but the temperature array is used for storing vorticity so I guess it is done by mistake.

**Comment by adampep** [comment]
No. I see now. It is stream function calculation. I will shorten the run then

**Pull request merged**
