### PR TITLE
First shock capturing cases for CMT-nek

### PR DESCRIPTION
**Pull request by hackljf**
I'll push READMEs for the two new CMT-nek cases sod3 and shock2, but I wanted to open the PR now.

### CODE REVIEW

**Comment by adampep** [comment]
Hi. One question. Do you need all the variables for linear simulation, mhd, moving meshes ....? If not, please set not used array sizes to 1 in SIZE, so we can reduce nek memory footprint. It as well gives some information to the user what arrays are necessary for given setup. Thank you.

**Comment by hackljf** [comment]
Thank you so much for addressing this issue. We had intended to set MHD
arrays and all the GMRES stuff to singletons in all dimensions. We are not
as well-trained as we should be, so if there are other things we missed
(especially during the migration to the new SIZE file format) we need to
get them fixed. I will revisit this issue tomorrow at the latest. We
haven't derived equations suitable for moving meshes yet; this is a very
distant goal at the present time

We also need to put a README in both CMT subdirectories.

-- 

Jason Hackl

**Comment by hackljf** [comment]
I am asking for a little bit of guidance on better determining which array sizes need to be 1 in the SIZE file to get this PR accepted. They will also affect short_tests/CMT/inviscid_vortex, and could substantially speed it up for the sake of regression testing. We have also updated the sod NekExample, and want to make sure our use of the SIZE file is cautious yet correct before updating this PR further.

**Comment by adampep** [comment]
Hi. Sorry for late response. I was thinking about arrays you do not need for your simulation . For example you do not need magnetic field, so lbelt can be 1. The same about perturbation (lpert = 1) or mesh solver (lx1m = 1). Anyhow it is not the most important problem (I can fix it later myself). Right now the code does not compile because cmt_ics requires my_full_restart and tat one is missing. Two other points:
- readme describes two cases but there are three directories. What about pvort? Should it be there? This code gives additional errors during compilation (not proper variable declaration)
- these examples are not added to NekTests.py. If we are going to run them as test cases there should be some testing variables we can check. Can you provide one?

**Comment by hackljf** [comment]
Thanks for getting back in touch and pointing out a couple places we can
save precious memory. Sorry we didn't update NekExamples when we updated
cmt-nek.

We actually folded in a lot of code into CMt. Once it's working in 3D we
will update NekExamples

**Comment by hackljf** [comment]
One more thing I should mention is that short_tests/CMT/inviscid_vortex in
github.com/Nek5000/Nek5000.git has been kept up-to-date during all of our
code development. The README and shock-capturing cases in NekExamples will
be brought up to that version of the code. I promise this pull request will
include up-to-date and fully functional code before Friday of this week.

**Comment by hackljf** [comment]
This is intended as a "companion" to https://github.com/Nek5000/Nek5000/pull/372, and this code will not run without it.

I pared down the SIZE file a little, but I was not able to

run with lbelt=1.  The code segfaulted in a vector dssum in setics

nor was I able to run with lx1m=1 (in retrospect, I should have tried lx1m=2 because zwgjd complained about Gauss points)

Thank you for everything, Adam and Stefan.

**Comment by hackljf** [comment]
Is inclusion in NekTests.py mandatory? Likewise, do you think it's necessary to put short_tests/CMT/inviscid_vortex in NekExamples?

**Comment by adampep** [comment]
Sorry for the slow work on it. Could you provide .par instead of .rea. We would like to improve functionality of .par. If there is any runtime parameter missing please report it in Nek5000 issues

**Comment by hackljf** [comment]
I am grateful that you have not forgotten us. I have fallen behind
(publishing this work has become very drawn-out) as well. I do not have any
idea what a .par file is at all. Is it documented anywhere? I will catch up.

I had left off at following the other NekExamples and preparing a python
unittest for all shock capturing cases I had intended to submit to
NekExamples. I know you need both, but what would be more useful to do
first: .par file or the python tests in NekTests.py?

**Comment by adampep** [comment]
Hi,
I was working on your example to add it to NekTest. However, I found strange dependency with the SIZE file. Even though you do not seem to reference lbelt in your cmt code, setting this variable to 1 gives strange initialization error related to not proper setting of gs communicator. It looks like some memory problem, but I couldn't figure it out. Could you take a look at it? I've uploaded my slightly modified version of your example to 
https://github.com/KTH-ExaFlow/NekExamples.git
You will find there CmdSod3 branch. I wanted to make pull your repository, but it was not updated for some time so I left it just on my repository.
Regards
Adam

**Comment by hackljf** [comment]
Thanks for your attention and help with this. We've run a long time with
lbelt set to whatever its default is in nek. We ARE Admittedly using a gs
handle that is obsolete/very old (cmt/face.f). It was the first one Paul
wrote for DG. If lbelt>1 is completely unacceptable for mere demonstration
and dissemination of the first shock-capturing cases to the wider nek
community, then what I suggest (until I can look at it) is to try lbelt=1
with discontinuous Galerkin transport of scalars (IFDG=T, no CMTNEK) and
see if that works. If it does, then we need to migrate to the newer gs
handle for DG. I will look at this tonight, but don't have any obvious
ideas about what is causing the problem.

**Comment by hackljf** [comment]
I will have our repositories and UFCCMT up to date by Monday. The shift
away from nx1 spooked us a little, but looking at the cmt directory and
short_tests convinces me that getting all our usr files up to date should
be trivial.

**Comment by hackljf** [comment]
Dear Adam,

We ran your CmtSod3 example on an intel cluster (I can send more specs
later) with Intel Fortran Compiler 2016.0.109 and OpenMPI 1.10.2, no
optimizations and -g. The DDT debugger reported that nelgv was being
overwritten (zeroed out) in nekuic at line 1692 in e=30, far outside the
bounds of bz with lbelt=1. Like most short_tests, we run with npscal=0, and
the code appears to set ifldmhd=3+npscal without regard to ifmhd. When
ldimt is high enough (we set it to 6), bx by and bz get set in nekuic,
again, without regard for IFMHD. I confess that we are not using ifield
correctly in our code and even abuse ldimt for diagnostic purposes. I also
concede we need to migrate to the DG operators in conduct.f and use IFDG.
Nevertheless, I propose that lines 1689-1692 be executed only IFMHD=.true.
Is this an acceptable solution to the problem?

Thank you so much again for sticking with us.

**Comment by hackljf** [comment]
I got everything to work with ldimt_proj=1, lpert=1, mxprev=1,lgmres=1, lx1m=1, lbelt=1, lpelt=1 and lcvelt=1. IFLDMHD is set to an arbitrarily large integer and will be so set in all CMT-nek cases with ldimt > 3 until line nekuic checks bx against IFMHD.

**Comment by adampep** [comment]
Good job! Thank you for your effort. I'm merging it right now. The only changes I've made is removing some commented code parts and putting back error calculation, as this is the way to check correctness of the solution in jenkins. Once again thank you.

**Comment by hackljf** [comment]
Thank YOU! This is a huge day for CMT-nek. I will educate myself on unit
tests in python. Thank you so much for helping me clear that hurdle.

**Comment by adampep** [comment]
merged in  2147576

**Pull request closed without merging**
